# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for AI Agent Workbench v3.11"""

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('config/config.yaml', 'config'),
        ('resources/themes/dark_github.qss', 'resources/themes'),
        ('resources/themes/trae_dark.qss', 'resources/themes'),
        (r'venv\Lib\site-packages\certifi\cacert.pem', 'certifi'),
    ],
    hiddenimports=[
        # Core infrastructure
        'yaml',
        'core.event_bus',
        'core.events',
        # v4 single-track architecture
        'v4.main_window',
        'v4.events',
        'v4.event_bus',
        'v4.orchestrator',
        'v4.worker',
        'v4.worker_manager',
        'v4.runtime',
        'v4.repository',
        'v4.queue',
        'v4.ui_renderer',
        'v4.conversation_list',
        'v4.models',
        # v4 agent_engine engines
        'agent_engine',
        'agent_engine.llm_registry',
        'agent_engine.memory_manager',
        'agent_engine.phase_manager',
        'agent_engine.orchestrator',
        'agent_engine.agent_session',
        'agent_engine.engines',
        'agent_engine.engines.interfaces',
        'agent_engine.engines.context_engine',
        'agent_engine.engines.prompt_engine',
        'agent_engine.engines.inference_engine',
        'agent_engine.engines.tool_engine',
        'agent_engine.engines.phase_engine',
        'agent_engine.engines.memory_engine',
        'agent_engine.engines.metrics_engine',
        'agent_engine.engines.policy_engine',
        # tools
        'tools',
        'tools.system',
        'tools.quant',
        'tools.mt5',
        'tools.external_apis',
        'tools.screen',
        # workers
        'workers',
        'workers.agent_worker',
        'workers.base_worker',
        'workers.terminal_worker',
        'workers.session_task',
        'workers.task_capacity',
        'workers.task_queue',
        'workers.worker_pool',
        # services still referenced by tests / fallback paths
        'services',
        'services.pending_queue',
        'services.task_service',
        'services.config_service',
        'services.session_service',
        'services.theme_service',
        'services.project_service',
        'services.activity_service',
        'services.context_service',
        'services.path_resolver',
        'services.metrics_collector',
        'services.interpreter_service',
        'services.persistence_service',
        'services.mcp_service',
        # markdown & web parsing
        'markdown',
        'markdown.extensions.fenced_code',
        'markdown.extensions.tables',
        'markdown.extensions.nl2br',
        'markdown.extensions.codehilite',
        'bs4',
        'lxml',
        'html5lib',
        # others
        'dotenv',
        'sqlite3',
        'certifi',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=['scripts/runtime_hook.py'],
    excludes=[
        'PySide6.QtWebEngine', 'PySide6.QtWebEngineCore', 'PySide6.QtWebEngineWidgets',
        'PySide6.QtWebSockets', 'PySide6.QtWebChannel',
        'PySide6.QtSql', 'PySide6.QtQml', 'PySide6.QtQuick',
        'PySide6.QtMultimedia', 'PySide6.QtMultimediaWidgets',
        'PySide6.QtBluetooth', 'PySide6.QtNfc',
        'PySide6.QtSensors', 'PySide6.QtSerialPort',
        'PySide6.QtPositioning', 'PySide6.QtLocation',
        'PySide6.QtTextToSpeech', 'PySide6.QtHelp',
        'PySide6.QtAxContainer', 'PySide6.QtQuickWidgets',
        'PySide6.QtQuickControls2', 'PySide6.QtDataVisualization',
        'setuptools', 'pip', 'wheel', 'pkg_resources',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='AgentWorkbench',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['assets/app.ico'],
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='AgentWorkbench',
)
