# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for AI Agent Workbench v2"""

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('config.yaml', '.'),
        ('resources/themes/dark_github.qss', 'resources/themes'),
    ],
    hiddenimports=[
        'yaml',
        'markdown',
        'markdown.extensions.fenced_code',
        'markdown.extensions.tables',
        'markdown.extensions.nl2br',
        'markdown.extensions.codehilite',
        'dotenv',
        'sqlite3',
        'agent_engine',
        'agent_engine.mode_manager',
        'agent_engine.llm_registry',
        'agent_engine.memory_manager',
        'agent_engine.proactive_engine',
        'tools',
        'tools.system',
        'tools.quant',
        'tools.mt5',
        'tools.external_apis',
        'ui',
        'ui.main_window',
        'ui.chat_view',
        'ui.widgets',
        'ui.widgets.sidebar',
        'ui.widgets.conversation',
        'ui.widgets.tasks',
        'ui.widgets.terminal',
        'ui.widgets.status_indicator',
        'ui.dialogs',
        'ui.dialogs.settings',
        'workers',
        'workers.agent_worker',
        'workers.terminal_worker',
        'services',
        'services.config_service',
        'services.session_service',
        'services.theme_service',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='AgentWorkbench',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['app.ico'],
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='AgentWorkbench',
)
