# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for AI Agent Workbench v2"""

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('config.yaml', '.'),
        ('resources/themes/dark_github.qss', 'resources/themes'),
        (r'venv\Lib\site-packages\certifi\cacert.pem', 'certifi'),
    ],
    hiddenimports=[
        'yaml',
        'markdown',
        'markdown.extensions.fenced_code',
        'bs4',
        'lxml',
        'html5lib',
        'markdown.extensions.tables',
        'markdown.extensions.nl2br',
        'markdown.extensions.codehilite',
        'dotenv',
        'sqlite3',
        'certifi',
        'agent_engine',
        'agent_engine.mode_manager',
        'agent_engine.llm_registry',
        'agent_engine.memory_manager',
        'agent_engine.proactive_engine',
        'agent_engine.phase_manager',
        'agent_engine.classifier',
        'agent_engine.orchestrator',
        'tools',
        'tools.system',
        'tools.quant',
        'tools.mt5',
        'tools.external_apis',
        'ui',
        'ui.main_window',
        'ui.chat_view',
        'ui.widgets',
        'ui.widgets.sidebar',
        'ui.widgets.conversation',
        'ui.widgets.tasks',
        'ui.widgets.terminal',
        'ui.widgets.status_indicator',
        'ui.widgets.workspace',
        'ui.widgets.document_editor',
        'ui.widgets.activity_panel',
        'ui.dialogs',
        'ui.dialogs.settings',
        'workers',
        'workers.agent_worker',
        'workers.terminal_worker',
        'services',
        'services.config_service',
        'services.session_service',
        'services.theme_service',
        'services.project_service',
        'services.activity_service',
        'services.context_service',
        'services.path_resolver',
        'services.metrics_collector',
        'services.interpreter_service',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=['runtime_hook.py'],
    excludes=[
        'PySide6.QtWebEngine', 'PySide6.QtWebEngineCore', 'PySide6.QtWebEngineWidgets',
        'PySide6.QtWebSockets', 'PySide6.QtWebChannel',
        'PySide6.QtSql', 'PySide6.QtQml', 'PySide6.QtQuick',
        'PySide6.QtMultimedia', 'PySide6.QtMultimediaWidgets',
        'PySide6.QtBluetooth', 'PySide6.QtNfc',
        'PySide6.QtSensors', 'PySide6.QtSerialPort',
        'PySide6.QtPositioning', 'PySide6.QtLocation',
        'PySide6.QtTextToSpeech', 'PySide6.QtHelp',
        'PySide6.QtAxContainer', 'PySide6.QtQuickWidgets',
        'PySide6.QtQuickControls2', 'PySide6.QtDataVisualization',
        'setuptools', 'pip', 'wheel', 'pkg_resources',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='AgentWorkbench',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['app.ico'],
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='AgentWorkbench',
)
